#!/bin/bash
if [ "$1" = "" ]
then
    filename="extra"
else
    filename="$1"
fi
aspell -c $filename -l "en"
awk '!x[$0]++' $filename > ${filename}.fix
diff $filename ${filename}.fix && rm -f ${filename}.fix
